services:
  - type: web
    name: fitiq-backend
    runtime: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: OPENAI_API_KEY
        fromEnv: OPENAI_API_KEY
